# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_v2.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget, QInputDialog, QLineEdit, QFileDialog
from main_logic import gsheets
from classes import pm_doc, specie


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1184, 899)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.lbl_info = QtWidgets.QLabel(self.centralwidget)
        self.lbl_info.setGeometry(QtCore.QRect(10, 10, 1171, 91))
        self.lbl_info.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_info.setObjectName("lbl_info")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 220, 491, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 190, 501, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(510, 110, 16, 741))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(520, 690, 661, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(530, 110, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(10, 850, 1171, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")

        self.tb_save = QtWidgets.QToolButton(self.centralwidget)
        self.tb_save.setGeometry(QtCore.QRect(530, 150, 591, 41))
        self.tb_save.setObjectName("tb_save")

        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(530, 300, 581, 51))
        self.checkBox.setObjectName("checkBox")

        self.tb_img = QtWidgets.QToolButton(self.centralwidget)
        self.tb_img.setGeometry(QtCore.QRect(530, 200, 591, 41))
        self.tb_img.setObjectName("tb_img")

        self.tb_maps = QtWidgets.QToolButton(self.centralwidget)
        self.tb_maps.setGeometry(QtCore.QRect(530, 250, 591, 41))
        self.tb_maps.setObjectName("tb_maps")

        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(540, 820, 641, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")

        self.bt_main = QtWidgets.QPushButton(self.centralwidget)
        self.bt_main.setGeometry(QtCore.QRect(530, 710, 471, 91))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.bt_main.setFont(font)
        self.bt_main.setObjectName("bt_main")

        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 121, 481, 41))
        self.layoutWidget.setObjectName("layoutWidget")

        self.site = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.site.setContentsMargins(0, 0, 0, 0)
        self.site.setObjectName("site")

        self.lbl_site = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_site.setObjectName("lbl_site")
        self.site.addWidget(self.lbl_site)
        self.cb_site = QtWidgets.QComboBox(self.layoutWidget)
        self.cb_site.setObjectName("cb_site")
        self.site.addWidget(self.cb_site)

        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 250, 481, 591))
        self.layoutWidget1.setObjectName("layoutWidget1")

        self.chapters = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.chapters.setContentsMargins(0, 0, 0, 0)
        self.chapters.setObjectName("chapters")

        self.cb_ch1 = QtWidgets.QComboBox(self.layoutWidget1)
        self.cb_ch1.setObjectName("cb_ch1")
        self.cb_ch1.addItem("")
        self.cb_ch1.addItem("")
        self.cb_ch1.addItem("")
        self.cb_ch1.addItem("")
        self.cb_ch1.addItem("")
        self.cb_ch1.addItem("")
        self.cb_ch1.addItem("")
        self.cb_ch1.addItem("")
        self.cb_ch1.addItem("")
        self.cb_ch1.addItem("")
        self.cb_ch1.addItem("")
        self.cb_ch1.addItem("")
        self.cb_ch1.addItem("")
        self.cb_ch1.addItem("")
        self.cb_ch1.addItem("")
        self.cb_ch1.addItem("")
        self.chapters.addWidget(self.cb_ch1)

        self.cb_ch2 = QtWidgets.QComboBox(self.layoutWidget1)
        self.cb_ch2.setObjectName("cb_ch2")
        self.cb_ch2.addItem("")
        self.cb_ch2.addItem("")
        self.cb_ch2.addItem("")
        self.cb_ch2.addItem("")
        self.cb_ch2.addItem("")
        self.cb_ch2.addItem("")
        self.cb_ch2.addItem("")
        self.cb_ch2.addItem("")
        self.cb_ch2.addItem("")
        self.cb_ch2.addItem("")
        self.cb_ch2.addItem("")
        self.cb_ch2.addItem("")
        self.cb_ch2.addItem("")
        self.cb_ch2.addItem("")
        self.cb_ch2.addItem("")
        self.cb_ch2.addItem("")
        self.chapters.addWidget(self.cb_ch2)

        self.cb_ch3 = QtWidgets.QComboBox(self.layoutWidget1)
        self.cb_ch3.setObjectName("cb_ch3")
        self.cb_ch3.addItem("")
        self.cb_ch3.addItem("")
        self.cb_ch3.addItem("")
        self.cb_ch3.addItem("")
        self.cb_ch3.addItem("")
        self.cb_ch3.addItem("")
        self.cb_ch3.addItem("")
        self.cb_ch3.addItem("")
        self.cb_ch3.addItem("")
        self.cb_ch3.addItem("")
        self.cb_ch3.addItem("")
        self.cb_ch3.addItem("")
        self.cb_ch3.addItem("")
        self.cb_ch3.addItem("")
        self.cb_ch3.addItem("")
        self.cb_ch3.addItem("")
        self.chapters.addWidget(self.cb_ch3)

        self.cb_ch4 = QtWidgets.QComboBox(self.layoutWidget1)
        self.cb_ch4.setObjectName("cb_ch4")
        self.cb_ch4.addItem("")
        self.cb_ch4.addItem("")
        self.cb_ch4.addItem("")
        self.cb_ch4.addItem("")
        self.cb_ch4.addItem("")
        self.cb_ch4.addItem("")
        self.cb_ch4.addItem("")
        self.cb_ch4.addItem("")
        self.cb_ch4.addItem("")
        self.cb_ch4.addItem("")
        self.cb_ch4.addItem("")
        self.cb_ch4.addItem("")
        self.cb_ch4.addItem("")
        self.cb_ch4.addItem("")
        self.cb_ch4.addItem("")
        self.cb_ch4.addItem("")
        self.chapters.addWidget(self.cb_ch4)

        self.cb_ch5 = QtWidgets.QComboBox(self.layoutWidget1)
        self.cb_ch5.setObjectName("cb_ch5")
        self.cb_ch5.addItem("")
        self.cb_ch5.addItem("")
        self.cb_ch5.addItem("")
        self.cb_ch5.addItem("")
        self.cb_ch5.addItem("")
        self.cb_ch5.addItem("")
        self.cb_ch5.addItem("")
        self.cb_ch5.addItem("")
        self.cb_ch5.addItem("")
        self.cb_ch5.addItem("")
        self.cb_ch5.addItem("")
        self.cb_ch5.addItem("")
        self.cb_ch5.addItem("")
        self.cb_ch5.addItem("")
        self.cb_ch5.addItem("")
        self.cb_ch5.addItem("")
        self.chapters.addWidget(self.cb_ch5)

        self.cb_ch6 = QtWidgets.QComboBox(self.layoutWidget1)
        self.cb_ch6.setObjectName("cb_ch6")
        self.cb_ch6.addItem("")
        self.cb_ch6.addItem("")
        self.cb_ch6.addItem("")
        self.cb_ch6.addItem("")
        self.cb_ch6.addItem("")
        self.cb_ch6.addItem("")
        self.cb_ch6.addItem("")
        self.cb_ch6.addItem("")
        self.cb_ch6.addItem("")
        self.cb_ch6.addItem("")
        self.cb_ch6.addItem("")
        self.cb_ch6.addItem("")
        self.cb_ch6.addItem("")
        self.cb_ch6.addItem("")
        self.cb_ch6.addItem("")
        self.cb_ch6.addItem("")
        self.chapters.addWidget(self.cb_ch6)

        self.cb_ch7 = QtWidgets.QComboBox(self.layoutWidget1)
        self.cb_ch7.setObjectName("cb_ch7")
        self.cb_ch7.addItem("")
        self.cb_ch7.addItem("")
        self.cb_ch7.addItem("")
        self.cb_ch7.addItem("")
        self.cb_ch7.addItem("")
        self.cb_ch7.addItem("")
        self.cb_ch7.addItem("")
        self.cb_ch7.addItem("")
        self.cb_ch7.addItem("")
        self.cb_ch7.addItem("")
        self.cb_ch7.addItem("")
        self.cb_ch7.addItem("")
        self.cb_ch7.addItem("")
        self.cb_ch7.addItem("")
        self.cb_ch7.addItem("")
        self.cb_ch7.addItem("")
        self.chapters.addWidget(self.cb_ch7)

        self.cb_ch8 = QtWidgets.QComboBox(self.layoutWidget1)
        self.cb_ch8.setObjectName("cb_ch8")
        self.cb_ch8.addItem("")
        self.cb_ch8.addItem("")
        self.cb_ch8.addItem("")
        self.cb_ch8.addItem("")
        self.cb_ch8.addItem("")
        self.cb_ch8.addItem("")
        self.cb_ch8.addItem("")
        self.cb_ch8.addItem("")
        self.cb_ch8.addItem("")
        self.cb_ch8.addItem("")
        self.cb_ch8.addItem("")
        self.cb_ch8.addItem("")
        self.cb_ch8.addItem("")
        self.cb_ch8.addItem("")
        self.cb_ch8.addItem("")
        self.cb_ch8.addItem("")
        self.chapters.addWidget(self.cb_ch8)
        
        self.cb_ch9 = QtWidgets.QComboBox(self.layoutWidget1)
        self.cb_ch9.setObjectName("cb_ch9")
        self.cb_ch9.addItem("")
        self.cb_ch9.addItem("")
        self.cb_ch9.addItem("")
        self.cb_ch9.addItem("")
        self.cb_ch9.addItem("")
        self.cb_ch9.addItem("")
        self.cb_ch9.addItem("")
        self.cb_ch9.addItem("")
        self.cb_ch9.addItem("")
        self.cb_ch9.addItem("")
        self.cb_ch9.addItem("")
        self.cb_ch9.addItem("")
        self.cb_ch9.addItem("")
        self.cb_ch9.addItem("")
        self.cb_ch9.addItem("")
        self.cb_ch9.addItem("")
        self.chapters.addWidget(self.cb_ch9)

        self.cb_ch10 = QtWidgets.QComboBox(self.layoutWidget1)
        self.cb_ch10.setObjectName("cb_ch10")
        self.cb_ch10.addItem("")
        self.cb_ch10.addItem("")
        self.cb_ch10.addItem("")
        self.cb_ch10.addItem("")
        self.cb_ch10.addItem("")
        self.cb_ch10.addItem("")
        self.cb_ch10.addItem("")
        self.cb_ch10.addItem("")
        self.cb_ch10.addItem("")
        self.cb_ch10.addItem("")
        self.cb_ch10.addItem("")
        self.cb_ch10.addItem("")
        self.cb_ch10.addItem("")
        self.cb_ch10.addItem("")
        self.cb_ch10.addItem("")
        self.cb_ch10.addItem("")
        self.chapters.addWidget(self.cb_ch10)

        self.cb_ch11 = QtWidgets.QComboBox(self.layoutWidget1)
        self.cb_ch11.setObjectName("cb_ch11")
        self.cb_ch11.addItem("")
        self.cb_ch11.addItem("")
        self.cb_ch11.addItem("")
        self.cb_ch11.addItem("")
        self.cb_ch11.addItem("")
        self.cb_ch11.addItem("")
        self.cb_ch11.addItem("")
        self.cb_ch11.addItem("")
        self.cb_ch11.addItem("")
        self.cb_ch11.addItem("")
        self.cb_ch11.addItem("")
        self.cb_ch11.addItem("")
        self.cb_ch11.addItem("")
        self.cb_ch11.addItem("")
        self.cb_ch11.addItem("")
        self.cb_ch11.addItem("")
        self.chapters.addWidget(self.cb_ch11)

        self.cb_ch12 = QtWidgets.QComboBox(self.layoutWidget1)
        self.cb_ch12.setObjectName("cb_ch12")
        self.cb_ch12.addItem("")
        self.cb_ch12.addItem("")
        self.cb_ch12.addItem("")
        self.cb_ch12.addItem("")
        self.cb_ch12.addItem("")
        self.cb_ch12.addItem("")
        self.cb_ch12.addItem("")
        self.cb_ch12.addItem("")
        self.cb_ch12.addItem("")
        self.cb_ch12.addItem("")
        self.cb_ch12.addItem("")
        self.cb_ch12.addItem("")
        self.cb_ch12.addItem("")
        self.cb_ch12.addItem("")
        self.cb_ch12.addItem("")
        self.cb_ch12.addItem("")
        self.chapters.addWidget(self.cb_ch12)

        self.cb_ch13 = QtWidgets.QComboBox(self.layoutWidget1)
        self.cb_ch13.setObjectName("cb_ch13")
        self.cb_ch13.addItem("")
        self.cb_ch13.addItem("")
        self.cb_ch13.addItem("")
        self.cb_ch13.addItem("")
        self.cb_ch13.addItem("")
        self.cb_ch13.addItem("")
        self.cb_ch13.addItem("")
        self.cb_ch13.addItem("")
        self.cb_ch13.addItem("")
        self.cb_ch13.addItem("")
        self.cb_ch13.addItem("")
        self.cb_ch13.addItem("")
        self.cb_ch13.addItem("")
        self.cb_ch13.addItem("")
        self.cb_ch13.addItem("")
        self.cb_ch13.addItem("")
        self.chapters.addWidget(self.cb_ch13)

        self.cb_ch14 = QtWidgets.QComboBox(self.layoutWidget1)
        self.cb_ch14.setObjectName("cb_ch14")
        self.cb_ch14.addItem("")
        self.cb_ch14.addItem("")
        self.cb_ch14.addItem("")
        self.cb_ch14.addItem("")
        self.cb_ch14.addItem("")
        self.cb_ch14.addItem("")
        self.cb_ch14.addItem("")
        self.cb_ch14.addItem("")
        self.cb_ch14.addItem("")
        self.cb_ch14.addItem("")
        self.cb_ch14.addItem("")
        self.cb_ch14.addItem("")
        self.cb_ch14.addItem("")
        self.cb_ch14.addItem("")
        self.cb_ch14.addItem("")
        self.cb_ch14.addItem("")
        self.chapters.addWidget(self.cb_ch14)

        self.cb_ch15 = QtWidgets.QComboBox(self.layoutWidget1)
        self.cb_ch15.setObjectName("cb_ch15")
        self.cb_ch15.addItem("")
        self.cb_ch15.addItem("")
        self.cb_ch15.addItem("")
        self.cb_ch15.addItem("")
        self.cb_ch15.addItem("")
        self.cb_ch15.addItem("")
        self.cb_ch15.addItem("")
        self.cb_ch15.addItem("")
        self.cb_ch15.addItem("")
        self.cb_ch15.addItem("")
        self.cb_ch15.addItem("")
        self.cb_ch15.addItem("")
        self.cb_ch15.addItem("")
        self.cb_ch15.addItem("")
        self.cb_ch15.addItem("")
        self.cb_ch15.addItem("")
        self.chapters.addWidget(self.cb_ch15)

        self.cb_ch16 = QtWidgets.QComboBox(self.layoutWidget1)
        self.cb_ch16.setObjectName("cb_ch16")
        self.cb_ch16.addItem("")
        self.cb_ch16.addItem("")
        self.cb_ch16.addItem("")
        self.cb_ch16.addItem("")
        self.cb_ch16.addItem("")
        self.cb_ch16.addItem("")
        self.cb_ch16.addItem("")
        self.cb_ch16.addItem("")
        self.cb_ch16.addItem("")
        self.cb_ch16.addItem("")
        self.cb_ch16.addItem("")
        self.cb_ch16.addItem("")
        self.cb_ch16.addItem("")
        self.cb_ch16.addItem("")
        self.cb_ch16.addItem("")
        self.cb_ch16.addItem("")
        self.chapters.addWidget(self.cb_ch16)

        self.cb_ch17 = QtWidgets.QComboBox(self.layoutWidget1)
        self.cb_ch17.setObjectName("cb_ch17")
        self.cb_ch17.addItem("")
        self.cb_ch17.addItem("")
        self.cb_ch17.addItem("")
        self.cb_ch17.addItem("")
        self.cb_ch17.addItem("")
        self.cb_ch17.addItem("")
        self.cb_ch17.addItem("")
        self.cb_ch17.addItem("")
        self.cb_ch17.addItem("")
        self.cb_ch17.addItem("")
        self.cb_ch17.addItem("")
        self.cb_ch17.addItem("")
        self.cb_ch17.addItem("")
        self.cb_ch17.addItem("")
        self.cb_ch17.addItem("")
        self.cb_ch17.addItem("")
        self.chapters.addWidget(self.cb_ch17)

        self.cb_ch18 = QtWidgets.QComboBox(self.layoutWidget1)
        self.cb_ch18.setObjectName("cb_ch18")
        self.cb_ch18.addItem("")
        self.cb_ch18.addItem("")
        self.cb_ch18.addItem("")
        self.cb_ch18.addItem("")
        self.cb_ch18.addItem("")
        self.cb_ch18.addItem("")
        self.cb_ch18.addItem("")
        self.cb_ch18.addItem("")
        self.cb_ch18.addItem("")
        self.cb_ch18.addItem("")
        self.cb_ch18.addItem("")
        self.cb_ch18.addItem("")
        self.cb_ch18.addItem("")
        self.cb_ch18.addItem("")
        self.cb_ch18.addItem("")
        self.cb_ch18.addItem("")
        self.chapters.addWidget(self.cb_ch18)

        self.cb_ch19 = QtWidgets.QComboBox(self.layoutWidget1)
        self.cb_ch19.setObjectName("cb_ch19")
        self.cb_ch19.addItem("")
        self.cb_ch19.addItem("")
        self.cb_ch19.addItem("")
        self.cb_ch19.addItem("")
        self.cb_ch19.addItem("")
        self.cb_ch19.addItem("")
        self.cb_ch19.addItem("")
        self.cb_ch19.addItem("")
        self.cb_ch19.addItem("")
        self.cb_ch19.addItem("")
        self.cb_ch19.addItem("")
        self.cb_ch19.addItem("")
        self.cb_ch19.addItem("")
        self.cb_ch19.addItem("")
        self.cb_ch19.addItem("")
        self.cb_ch19.addItem("")
        self.chapters.addWidget(self.cb_ch19)

        self.lgbx = QtWidgets.QTextBrowser(self.centralwidget)
        self.lgbx.setGeometry(QtCore.QRect(530, 380, 641, 311))
        self.lgbx.setObjectName("lgbx")

        self.bt_cons = QtWidgets.QPushButton(self.centralwidget)
        self.bt_cons.setGeometry(QtCore.QRect(1010, 710, 161, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bt_cons.setFont(font)
        self.bt_cons.setObjectName("bt_cons")

        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1184, 21))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.actionAdd_site = QtWidgets.QAction(MainWindow)
        self.actionAdd_site.setObjectName("actionAdd_site")
        self.menuSettings.addAction(self.actionAdd_site)

        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



#My code in Ui_MainWindow
        #Setting the sites in site combo box
        for i in list(gsheets.keys()):
            self.cb_site.addItem(i)

    #Setting the select folders buttons
        self.tb_save.clicked.connect(lambda: self.fp_dialog(self.tb_save))
        self.tb_img.clicked.connect(lambda: self.fp_dialog(self.tb_img))
        self.tb_maps.clicked.connect(lambda: self.fp_dialog(self.tb_maps))

#Setting diferent functions in the main class
    #The function that opens the select folders buttons
    def fp_dialog(self,btn):
        foldername = QFileDialog.getExistingDirectory()
        if foldername != '':
            btn.setText(foldername) 

    #The main function responsible for result
    def create_doc_func(self):
        #Getting the parameters
        self.site = str(self.cb_site.currentText())
        self.save_path = str(self.tb_save.text())
        self.img_path = str(self.tb_img.text())
        self.maps_path = str(self.tb_maps.text())
        self.titles = self.ch_titles.isChecked()
        self.empty_tables = self.checkBox.isChecked()

        self.cb1_txt = str(cb_ch1.currentText())
        self.cb2_txt = str(cb_ch2.currentText())
        self.cb3_txt = str(cb_ch3.currentText())
        self.cb4_txt = str(cb_ch4.currentText())
        self.cb5_txt = str(cb_ch5.currentText())
        self.cb6_txt = str(cb_ch6.currentText())
        self.cb7_txt = str(cb_ch7.currentText())
        self.cb8_txt = str(cb_ch8.currentText())
        self.cb9_txt = str(cb_ch9.currentText())
        self.cb10_txt = str(cb_ch10.currentText())
        self.cb11_txt = str(cb_ch11.currentText())
        self.cb12_txt = str(cb_ch12.currentText())
        self.cb13_txt = str(cb_ch13.currentText())
        self.cb14_txt = str(cb_ch14.currentText())
        self.cb15_txt = str(cb_ch15.currentText())
        self.cb16_txt = str(cb_ch16.currentText())
        self.cb17_txt = str(cb_ch17.currentText())







        doc = pm_doc()






















    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_info.setText(_translate("MainWindow", "Here is the informative text"))
        self.label.setText(_translate("MainWindow", "Doc format! (Choose the chapters/tables in the desired order)"))
        self.label_2.setText(_translate("MainWindow", "Options"))
        self.tb_save.setText(_translate("MainWindow", "Choose where to save the file!"))
        self.checkBox.setText(_translate("MainWindow", "I want empty tables! If checked the tables will be exported empty."))
        self.tb_img.setText(_translate("MainWindow", "Choose the species photos folder!"))
        self.tb_maps.setText(_translate("MainWindow", "Choose the species maps folder!"))
        self.bt_main.setText(_translate("MainWindow", "Create document!"))
        self.lbl_site.setText(_translate("MainWindow", "Select the site!"))
        self.cb_ch1.setItemText(0, _translate("MainWindow", "empty"))
        self.cb_ch1.setItemText(1, _translate("MainWindow", "Create a species header"))
        self.cb_ch1.setItemText(2, _translate("MainWindow", "Create descriptive table A"))
        self.cb_ch1.setItemText(3, _translate("MainWindow", "Create descriptive table B"))
        self.cb_ch1.setItemText(4, _translate("MainWindow", "Create population conservation table"))
        self.cb_ch1.setItemText(5, _translate("MainWindow", "Create habitat conservation table"))
        self.cb_ch1.setItemText(6, _translate("MainWindow", "Create perspectives conservation table"))
        self.cb_ch1.setItemText(7, _translate("MainWindow", "Create global conservation table"))
        self.cb_ch1.setItemText(8, _translate("MainWindow", "Create matrix 1 table"))
        self.cb_ch1.setItemText(9, _translate("MainWindow", "Create matrix 2 table"))
        self.cb_ch1.setItemText(10, _translate("MainWindow", "Create matrix 3 table"))
        self.cb_ch1.setItemText(11, _translate("MainWindow", "Create matrix 4 table"))
        self.cb_ch1.setItemText(12, _translate("MainWindow", "Create matrix 5 table"))
        self.cb_ch1.setItemText(13, _translate("MainWindow", "Create matrix 6 table"))
        self.cb_ch1.setItemText(14, _translate("MainWindow", "Create matrix 7 table"))
        self.cb_ch1.setItemText(15, _translate("MainWindow", "Create measures chapter"))
        self.cb_ch2.setItemText(0, _translate("MainWindow", "empty"))
        self.cb_ch2.setItemText(1, _translate("MainWindow", "Create a species header"))
        self.cb_ch2.setItemText(2, _translate("MainWindow", "Create descriptive table A"))
        self.cb_ch2.setItemText(3, _translate("MainWindow", "Create descriptive table B"))
        self.cb_ch2.setItemText(4, _translate("MainWindow", "Create population conservation table"))
        self.cb_ch2.setItemText(5, _translate("MainWindow", "Create habitat conservation table"))
        self.cb_ch2.setItemText(6, _translate("MainWindow", "Create perspectives conservation table"))
        self.cb_ch2.setItemText(7, _translate("MainWindow", "Create global conservation table"))
        self.cb_ch2.setItemText(8, _translate("MainWindow", "Create matrix 1 table"))
        self.cb_ch2.setItemText(9, _translate("MainWindow", "Create matrix 2 table"))
        self.cb_ch2.setItemText(10, _translate("MainWindow", "Create matrix 3 table"))
        self.cb_ch2.setItemText(11, _translate("MainWindow", "Create matrix 4 table"))
        self.cb_ch2.setItemText(12, _translate("MainWindow", "Create matrix 5 table"))
        self.cb_ch2.setItemText(13, _translate("MainWindow", "Create matrix 6 table"))
        self.cb_ch2.setItemText(14, _translate("MainWindow", "Create matrix 7 table"))
        self.cb_ch2.setItemText(15, _translate("MainWindow", "Create measures chapter"))
        self.cb_ch3.setItemText(0, _translate("MainWindow", "empty"))
        self.cb_ch3.setItemText(1, _translate("MainWindow", "Create a species header"))
        self.cb_ch3.setItemText(2, _translate("MainWindow", "Create descriptive table A"))
        self.cb_ch3.setItemText(3, _translate("MainWindow", "Create descriptive table B"))
        self.cb_ch3.setItemText(4, _translate("MainWindow", "Create population conservation table"))
        self.cb_ch3.setItemText(5, _translate("MainWindow", "Create habitat conservation table"))
        self.cb_ch3.setItemText(6, _translate("MainWindow", "Create perspectives conservation table"))
        self.cb_ch3.setItemText(7, _translate("MainWindow", "Create global conservation table"))
        self.cb_ch3.setItemText(8, _translate("MainWindow", "Create matrix 1 table"))
        self.cb_ch3.setItemText(9, _translate("MainWindow", "Create matrix 2 table"))
        self.cb_ch3.setItemText(10, _translate("MainWindow", "Create matrix 3 table"))
        self.cb_ch3.setItemText(11, _translate("MainWindow", "Create matrix 4 table"))
        self.cb_ch3.setItemText(12, _translate("MainWindow", "Create matrix 5 table"))
        self.cb_ch3.setItemText(13, _translate("MainWindow", "Create matrix 6 table"))
        self.cb_ch3.setItemText(14, _translate("MainWindow", "Create matrix 7 table"))
        self.cb_ch3.setItemText(15, _translate("MainWindow", "Create measures chapter"))
        self.cb_ch4.setItemText(0, _translate("MainWindow", "empty"))
        self.cb_ch4.setItemText(1, _translate("MainWindow", "Create a species header"))
        self.cb_ch4.setItemText(2, _translate("MainWindow", "Create descriptive table A"))
        self.cb_ch4.setItemText(3, _translate("MainWindow", "Create descriptive table B"))
        self.cb_ch4.setItemText(4, _translate("MainWindow", "Create population conservation table"))
        self.cb_ch4.setItemText(5, _translate("MainWindow", "Create habitat conservation table"))
        self.cb_ch4.setItemText(6, _translate("MainWindow", "Create perspectives conservation table"))
        self.cb_ch4.setItemText(7, _translate("MainWindow", "Create global conservation table"))
        self.cb_ch4.setItemText(8, _translate("MainWindow", "Create matrix 1 table"))
        self.cb_ch4.setItemText(9, _translate("MainWindow", "Create matrix 2 table"))
        self.cb_ch4.setItemText(10, _translate("MainWindow", "Create matrix 3 table"))
        self.cb_ch4.setItemText(11, _translate("MainWindow", "Create matrix 4 table"))
        self.cb_ch4.setItemText(12, _translate("MainWindow", "Create matrix 5 table"))
        self.cb_ch4.setItemText(13, _translate("MainWindow", "Create matrix 6 table"))
        self.cb_ch4.setItemText(14, _translate("MainWindow", "Create matrix 7 table"))
        self.cb_ch4.setItemText(15, _translate("MainWindow", "Create measures chapter"))
        self.cb_ch5.setItemText(0, _translate("MainWindow", "empty"))
        self.cb_ch5.setItemText(1, _translate("MainWindow", "Create a species header"))
        self.cb_ch5.setItemText(2, _translate("MainWindow", "Create descriptive table A"))
        self.cb_ch5.setItemText(3, _translate("MainWindow", "Create descriptive table B"))
        self.cb_ch5.setItemText(4, _translate("MainWindow", "Create population conservation table"))
        self.cb_ch5.setItemText(5, _translate("MainWindow", "Create habitat conservation table"))
        self.cb_ch5.setItemText(6, _translate("MainWindow", "Create perspectives conservation table"))
        self.cb_ch5.setItemText(7, _translate("MainWindow", "Create global conservation table"))
        self.cb_ch5.setItemText(8, _translate("MainWindow", "Create matrix 1 table"))
        self.cb_ch5.setItemText(9, _translate("MainWindow", "Create matrix 2 table"))
        self.cb_ch5.setItemText(10, _translate("MainWindow", "Create matrix 3 table"))
        self.cb_ch5.setItemText(11, _translate("MainWindow", "Create matrix 4 table"))
        self.cb_ch5.setItemText(12, _translate("MainWindow", "Create matrix 5 table"))
        self.cb_ch5.setItemText(13, _translate("MainWindow", "Create matrix 6 table"))
        self.cb_ch5.setItemText(14, _translate("MainWindow", "Create matrix 7 table"))
        self.cb_ch5.setItemText(15, _translate("MainWindow", "Create measures chapter"))
        self.cb_ch6.setItemText(0, _translate("MainWindow", "empty"))
        self.cb_ch6.setItemText(1, _translate("MainWindow", "Create a species header"))
        self.cb_ch6.setItemText(2, _translate("MainWindow", "Create descriptive table A"))
        self.cb_ch6.setItemText(3, _translate("MainWindow", "Create descriptive table B"))
        self.cb_ch6.setItemText(4, _translate("MainWindow", "Create population conservation table"))
        self.cb_ch6.setItemText(5, _translate("MainWindow", "Create habitat conservation table"))
        self.cb_ch6.setItemText(6, _translate("MainWindow", "Create perspectives conservation table"))
        self.cb_ch6.setItemText(7, _translate("MainWindow", "Create global conservation table"))
        self.cb_ch6.setItemText(8, _translate("MainWindow", "Create matrix 1 table"))
        self.cb_ch6.setItemText(9, _translate("MainWindow", "Create matrix 2 table"))
        self.cb_ch6.setItemText(10, _translate("MainWindow", "Create matrix 3 table"))
        self.cb_ch6.setItemText(11, _translate("MainWindow", "Create matrix 4 table"))
        self.cb_ch6.setItemText(12, _translate("MainWindow", "Create matrix 5 table"))
        self.cb_ch6.setItemText(13, _translate("MainWindow", "Create matrix 6 table"))
        self.cb_ch6.setItemText(14, _translate("MainWindow", "Create matrix 7 table"))
        self.cb_ch6.setItemText(15, _translate("MainWindow", "Create measures chapter"))
        self.cb_ch7.setItemText(0, _translate("MainWindow", "empty"))
        self.cb_ch7.setItemText(1, _translate("MainWindow", "Create a species header"))
        self.cb_ch7.setItemText(2, _translate("MainWindow", "Create descriptive table A"))
        self.cb_ch7.setItemText(3, _translate("MainWindow", "Create descriptive table B"))
        self.cb_ch7.setItemText(4, _translate("MainWindow", "Create population conservation table"))
        self.cb_ch7.setItemText(5, _translate("MainWindow", "Create habitat conservation table"))
        self.cb_ch7.setItemText(6, _translate("MainWindow", "Create perspectives conservation table"))
        self.cb_ch7.setItemText(7, _translate("MainWindow", "Create global conservation table"))
        self.cb_ch7.setItemText(8, _translate("MainWindow", "Create matrix 1 table"))
        self.cb_ch7.setItemText(9, _translate("MainWindow", "Create matrix 2 table"))
        self.cb_ch7.setItemText(10, _translate("MainWindow", "Create matrix 3 table"))
        self.cb_ch7.setItemText(11, _translate("MainWindow", "Create matrix 4 table"))
        self.cb_ch7.setItemText(12, _translate("MainWindow", "Create matrix 5 table"))
        self.cb_ch7.setItemText(13, _translate("MainWindow", "Create matrix 6 table"))
        self.cb_ch7.setItemText(14, _translate("MainWindow", "Create matrix 7 table"))
        self.cb_ch7.setItemText(15, _translate("MainWindow", "Create measures chapter"))
        self.cb_ch8.setItemText(0, _translate("MainWindow", "empty"))
        self.cb_ch8.setItemText(1, _translate("MainWindow", "Create a species header"))
        self.cb_ch8.setItemText(2, _translate("MainWindow", "Create descriptive table A"))
        self.cb_ch8.setItemText(3, _translate("MainWindow", "Create descriptive table B"))
        self.cb_ch8.setItemText(4, _translate("MainWindow", "Create population conservation table"))
        self.cb_ch8.setItemText(5, _translate("MainWindow", "Create habitat conservation table"))
        self.cb_ch8.setItemText(6, _translate("MainWindow", "Create perspectives conservation table"))
        self.cb_ch8.setItemText(7, _translate("MainWindow", "Create global conservation table"))
        self.cb_ch8.setItemText(8, _translate("MainWindow", "Create matrix 1 table"))
        self.cb_ch8.setItemText(9, _translate("MainWindow", "Create matrix 2 table"))
        self.cb_ch8.setItemText(10, _translate("MainWindow", "Create matrix 3 table"))
        self.cb_ch8.setItemText(11, _translate("MainWindow", "Create matrix 4 table"))
        self.cb_ch8.setItemText(12, _translate("MainWindow", "Create matrix 5 table"))
        self.cb_ch8.setItemText(13, _translate("MainWindow", "Create matrix 6 table"))
        self.cb_ch8.setItemText(14, _translate("MainWindow", "Create matrix 7 table"))
        self.cb_ch8.setItemText(15, _translate("MainWindow", "Create measures chapter"))
        self.cb_ch9.setItemText(0, _translate("MainWindow", "empty"))
        self.cb_ch9.setItemText(1, _translate("MainWindow", "Create a species header"))
        self.cb_ch9.setItemText(2, _translate("MainWindow", "Create descriptive table A"))
        self.cb_ch9.setItemText(3, _translate("MainWindow", "Create descriptive table B"))
        self.cb_ch9.setItemText(4, _translate("MainWindow", "Create population conservation table"))
        self.cb_ch9.setItemText(5, _translate("MainWindow", "Create habitat conservation table"))
        self.cb_ch9.setItemText(6, _translate("MainWindow", "Create perspectives conservation table"))
        self.cb_ch9.setItemText(7, _translate("MainWindow", "Create global conservation table"))
        self.cb_ch9.setItemText(8, _translate("MainWindow", "Create matrix 1 table"))
        self.cb_ch9.setItemText(9, _translate("MainWindow", "Create matrix 2 table"))
        self.cb_ch9.setItemText(10, _translate("MainWindow", "Create matrix 3 table"))
        self.cb_ch9.setItemText(11, _translate("MainWindow", "Create matrix 4 table"))
        self.cb_ch9.setItemText(12, _translate("MainWindow", "Create matrix 5 table"))
        self.cb_ch9.setItemText(13, _translate("MainWindow", "Create matrix 6 table"))
        self.cb_ch9.setItemText(14, _translate("MainWindow", "Create matrix 7 table"))
        self.cb_ch9.setItemText(15, _translate("MainWindow", "Create measures chapter"))
        self.cb_ch10.setItemText(0, _translate("MainWindow", "empty"))
        self.cb_ch10.setItemText(1, _translate("MainWindow", "Create a species header"))
        self.cb_ch10.setItemText(2, _translate("MainWindow", "Create descriptive table A"))
        self.cb_ch10.setItemText(3, _translate("MainWindow", "Create descriptive table B"))
        self.cb_ch10.setItemText(4, _translate("MainWindow", "Create population conservation table"))
        self.cb_ch10.setItemText(5, _translate("MainWindow", "Create habitat conservation table"))
        self.cb_ch10.setItemText(6, _translate("MainWindow", "Create perspectives conservation table"))
        self.cb_ch10.setItemText(7, _translate("MainWindow", "Create global conservation table"))
        self.cb_ch10.setItemText(8, _translate("MainWindow", "Create matrix 1 table"))
        self.cb_ch10.setItemText(9, _translate("MainWindow", "Create matrix 2 table"))
        self.cb_ch10.setItemText(10, _translate("MainWindow", "Create matrix 3 table"))
        self.cb_ch10.setItemText(11, _translate("MainWindow", "Create matrix 4 table"))
        self.cb_ch10.setItemText(12, _translate("MainWindow", "Create matrix 5 table"))
        self.cb_ch10.setItemText(13, _translate("MainWindow", "Create matrix 6 table"))
        self.cb_ch10.setItemText(14, _translate("MainWindow", "Create matrix 7 table"))
        self.cb_ch10.setItemText(15, _translate("MainWindow", "Create measures chapter"))
        self.cb_ch11.setItemText(0, _translate("MainWindow", "empty"))
        self.cb_ch11.setItemText(1, _translate("MainWindow", "Create a species header"))
        self.cb_ch11.setItemText(2, _translate("MainWindow", "Create descriptive table A"))
        self.cb_ch11.setItemText(3, _translate("MainWindow", "Create descriptive table B"))
        self.cb_ch11.setItemText(4, _translate("MainWindow", "Create population conservation table"))
        self.cb_ch11.setItemText(5, _translate("MainWindow", "Create habitat conservation table"))
        self.cb_ch11.setItemText(6, _translate("MainWindow", "Create perspectives conservation table"))
        self.cb_ch11.setItemText(7, _translate("MainWindow", "Create global conservation table"))
        self.cb_ch11.setItemText(8, _translate("MainWindow", "Create matrix 1 table"))
        self.cb_ch11.setItemText(9, _translate("MainWindow", "Create matrix 2 table"))
        self.cb_ch11.setItemText(10, _translate("MainWindow", "Create matrix 3 table"))
        self.cb_ch11.setItemText(11, _translate("MainWindow", "Create matrix 4 table"))
        self.cb_ch11.setItemText(12, _translate("MainWindow", "Create matrix 5 table"))
        self.cb_ch11.setItemText(13, _translate("MainWindow", "Create matrix 6 table"))
        self.cb_ch11.setItemText(14, _translate("MainWindow", "Create matrix 7 table"))
        self.cb_ch11.setItemText(15, _translate("MainWindow", "Create measures chapter"))
        self.cb_ch12.setItemText(0, _translate("MainWindow", "empty"))
        self.cb_ch12.setItemText(1, _translate("MainWindow", "Create a species header"))
        self.cb_ch12.setItemText(2, _translate("MainWindow", "Create descriptive table A"))
        self.cb_ch12.setItemText(3, _translate("MainWindow", "Create descriptive table B"))
        self.cb_ch12.setItemText(4, _translate("MainWindow", "Create population conservation table"))
        self.cb_ch12.setItemText(5, _translate("MainWindow", "Create habitat conservation table"))
        self.cb_ch12.setItemText(6, _translate("MainWindow", "Create perspectives conservation table"))
        self.cb_ch12.setItemText(7, _translate("MainWindow", "Create global conservation table"))
        self.cb_ch12.setItemText(8, _translate("MainWindow", "Create matrix 1 table"))
        self.cb_ch12.setItemText(9, _translate("MainWindow", "Create matrix 2 table"))
        self.cb_ch12.setItemText(10, _translate("MainWindow", "Create matrix 3 table"))
        self.cb_ch12.setItemText(11, _translate("MainWindow", "Create matrix 4 table"))
        self.cb_ch12.setItemText(12, _translate("MainWindow", "Create matrix 5 table"))
        self.cb_ch12.setItemText(13, _translate("MainWindow", "Create matrix 6 table"))
        self.cb_ch12.setItemText(14, _translate("MainWindow", "Create matrix 7 table"))
        self.cb_ch12.setItemText(15, _translate("MainWindow", "Create measures chapter"))
        self.cb_ch13.setItemText(0, _translate("MainWindow", "empty"))
        self.cb_ch13.setItemText(1, _translate("MainWindow", "Create a species header"))
        self.cb_ch13.setItemText(2, _translate("MainWindow", "Create descriptive table A"))
        self.cb_ch13.setItemText(3, _translate("MainWindow", "Create descriptive table B"))
        self.cb_ch13.setItemText(4, _translate("MainWindow", "Create population conservation table"))
        self.cb_ch13.setItemText(5, _translate("MainWindow", "Create habitat conservation table"))
        self.cb_ch13.setItemText(6, _translate("MainWindow", "Create perspectives conservation table"))
        self.cb_ch13.setItemText(7, _translate("MainWindow", "Create global conservation table"))
        self.cb_ch13.setItemText(8, _translate("MainWindow", "Create matrix 1 table"))
        self.cb_ch13.setItemText(9, _translate("MainWindow", "Create matrix 2 table"))
        self.cb_ch13.setItemText(10, _translate("MainWindow", "Create matrix 3 table"))
        self.cb_ch13.setItemText(11, _translate("MainWindow", "Create matrix 4 table"))
        self.cb_ch13.setItemText(12, _translate("MainWindow", "Create matrix 5 table"))
        self.cb_ch13.setItemText(13, _translate("MainWindow", "Create matrix 6 table"))
        self.cb_ch13.setItemText(14, _translate("MainWindow", "Create matrix 7 table"))
        self.cb_ch13.setItemText(15, _translate("MainWindow", "Create measures chapter"))
        self.cb_ch14.setItemText(0, _translate("MainWindow", "empty"))
        self.cb_ch14.setItemText(1, _translate("MainWindow", "Create a species header"))
        self.cb_ch14.setItemText(2, _translate("MainWindow", "Create descriptive table A"))
        self.cb_ch14.setItemText(3, _translate("MainWindow", "Create descriptive table B"))
        self.cb_ch14.setItemText(4, _translate("MainWindow", "Create population conservation table"))
        self.cb_ch14.setItemText(5, _translate("MainWindow", "Create habitat conservation table"))
        self.cb_ch14.setItemText(6, _translate("MainWindow", "Create perspectives conservation table"))
        self.cb_ch14.setItemText(7, _translate("MainWindow", "Create global conservation table"))
        self.cb_ch14.setItemText(8, _translate("MainWindow", "Create matrix 1 table"))
        self.cb_ch14.setItemText(9, _translate("MainWindow", "Create matrix 2 table"))
        self.cb_ch14.setItemText(10, _translate("MainWindow", "Create matrix 3 table"))
        self.cb_ch14.setItemText(11, _translate("MainWindow", "Create matrix 4 table"))
        self.cb_ch14.setItemText(12, _translate("MainWindow", "Create matrix 5 table"))
        self.cb_ch14.setItemText(13, _translate("MainWindow", "Create matrix 6 table"))
        self.cb_ch14.setItemText(14, _translate("MainWindow", "Create matrix 7 table"))
        self.cb_ch14.setItemText(15, _translate("MainWindow", "Create measures chapter"))
        self.cb_ch15.setItemText(0, _translate("MainWindow", "empty"))
        self.cb_ch15.setItemText(1, _translate("MainWindow", "Create a species header"))
        self.cb_ch15.setItemText(2, _translate("MainWindow", "Create descriptive table A"))
        self.cb_ch15.setItemText(3, _translate("MainWindow", "Create descriptive table B"))
        self.cb_ch15.setItemText(4, _translate("MainWindow", "Create population conservation table"))
        self.cb_ch15.setItemText(5, _translate("MainWindow", "Create habitat conservation table"))
        self.cb_ch15.setItemText(6, _translate("MainWindow", "Create perspectives conservation table"))
        self.cb_ch15.setItemText(7, _translate("MainWindow", "Create global conservation table"))
        self.cb_ch15.setItemText(8, _translate("MainWindow", "Create matrix 1 table"))
        self.cb_ch15.setItemText(9, _translate("MainWindow", "Create matrix 2 table"))
        self.cb_ch15.setItemText(10, _translate("MainWindow", "Create matrix 3 table"))
        self.cb_ch15.setItemText(11, _translate("MainWindow", "Create matrix 4 table"))
        self.cb_ch15.setItemText(12, _translate("MainWindow", "Create matrix 5 table"))
        self.cb_ch15.setItemText(13, _translate("MainWindow", "Create matrix 6 table"))
        self.cb_ch15.setItemText(14, _translate("MainWindow", "Create matrix 7 table"))
        self.cb_ch15.setItemText(15, _translate("MainWindow", "Create measures chapter"))
        self.cb_ch16.setItemText(0, _translate("MainWindow", "empty"))
        self.cb_ch16.setItemText(1, _translate("MainWindow", "Create a species header"))
        self.cb_ch16.setItemText(2, _translate("MainWindow", "Create descriptive table A"))
        self.cb_ch16.setItemText(3, _translate("MainWindow", "Create descriptive table B"))
        self.cb_ch16.setItemText(4, _translate("MainWindow", "Create population conservation table"))
        self.cb_ch16.setItemText(5, _translate("MainWindow", "Create habitat conservation table"))
        self.cb_ch16.setItemText(6, _translate("MainWindow", "Create perspectives conservation table"))
        self.cb_ch16.setItemText(7, _translate("MainWindow", "Create global conservation table"))
        self.cb_ch16.setItemText(8, _translate("MainWindow", "Create matrix 1 table"))
        self.cb_ch16.setItemText(9, _translate("MainWindow", "Create matrix 2 table"))
        self.cb_ch16.setItemText(10, _translate("MainWindow", "Create matrix 3 table"))
        self.cb_ch16.setItemText(11, _translate("MainWindow", "Create matrix 4 table"))
        self.cb_ch16.setItemText(12, _translate("MainWindow", "Create matrix 5 table"))
        self.cb_ch16.setItemText(13, _translate("MainWindow", "Create matrix 6 table"))
        self.cb_ch16.setItemText(14, _translate("MainWindow", "Create matrix 7 table"))
        self.cb_ch16.setItemText(15, _translate("MainWindow", "Create measures chapter"))
        self.cb_ch17.setItemText(0, _translate("MainWindow", "empty"))
        self.cb_ch17.setItemText(1, _translate("MainWindow", "Create a species header"))
        self.cb_ch17.setItemText(2, _translate("MainWindow", "Create descriptive table A"))
        self.cb_ch17.setItemText(3, _translate("MainWindow", "Create descriptive table B"))
        self.cb_ch17.setItemText(4, _translate("MainWindow", "Create population conservation table"))
        self.cb_ch17.setItemText(5, _translate("MainWindow", "Create habitat conservation table"))
        self.cb_ch17.setItemText(6, _translate("MainWindow", "Create perspectives conservation table"))
        self.cb_ch17.setItemText(7, _translate("MainWindow", "Create global conservation table"))
        self.cb_ch17.setItemText(8, _translate("MainWindow", "Create matrix 1 table"))
        self.cb_ch17.setItemText(9, _translate("MainWindow", "Create matrix 2 table"))
        self.cb_ch17.setItemText(10, _translate("MainWindow", "Create matrix 3 table"))
        self.cb_ch17.setItemText(11, _translate("MainWindow", "Create matrix 4 table"))
        self.cb_ch17.setItemText(12, _translate("MainWindow", "Create matrix 5 table"))
        self.cb_ch17.setItemText(13, _translate("MainWindow", "Create matrix 6 table"))
        self.cb_ch17.setItemText(14, _translate("MainWindow", "Create matrix 7 table"))
        self.cb_ch17.setItemText(15, _translate("MainWindow", "Create measures chapter"))
        self.cb_ch18.setItemText(0, _translate("MainWindow", "empty"))
        self.cb_ch18.setItemText(1, _translate("MainWindow", "Create a species header"))
        self.cb_ch18.setItemText(2, _translate("MainWindow", "Create descriptive table A"))
        self.cb_ch18.setItemText(3, _translate("MainWindow", "Create descriptive table B"))
        self.cb_ch18.setItemText(4, _translate("MainWindow", "Create population conservation table"))
        self.cb_ch18.setItemText(5, _translate("MainWindow", "Create habitat conservation table"))
        self.cb_ch18.setItemText(6, _translate("MainWindow", "Create perspectives conservation table"))
        self.cb_ch18.setItemText(7, _translate("MainWindow", "Create global conservation table"))
        self.cb_ch18.setItemText(8, _translate("MainWindow", "Create matrix 1 table"))
        self.cb_ch18.setItemText(9, _translate("MainWindow", "Create matrix 2 table"))
        self.cb_ch18.setItemText(10, _translate("MainWindow", "Create matrix 3 table"))
        self.cb_ch18.setItemText(11, _translate("MainWindow", "Create matrix 4 table"))
        self.cb_ch18.setItemText(12, _translate("MainWindow", "Create matrix 5 table"))
        self.cb_ch18.setItemText(13, _translate("MainWindow", "Create matrix 6 table"))
        self.cb_ch18.setItemText(14, _translate("MainWindow", "Create matrix 7 table"))
        self.cb_ch18.setItemText(15, _translate("MainWindow", "Create measures chapter"))
        self.cb_ch19.setItemText(0, _translate("MainWindow", "empty"))
        self.cb_ch19.setItemText(1, _translate("MainWindow", "Create a species header"))
        self.cb_ch19.setItemText(2, _translate("MainWindow", "Create descriptive table A"))
        self.cb_ch19.setItemText(3, _translate("MainWindow", "Create descriptive table B"))
        self.cb_ch19.setItemText(4, _translate("MainWindow", "Create population conservation table"))
        self.cb_ch19.setItemText(5, _translate("MainWindow", "Create habitat conservation table"))
        self.cb_ch19.setItemText(6, _translate("MainWindow", "Create perspectives conservation table"))
        self.cb_ch19.setItemText(7, _translate("MainWindow", "Create global conservation table"))
        self.cb_ch19.setItemText(8, _translate("MainWindow", "Create matrix 1 table"))
        self.cb_ch19.setItemText(9, _translate("MainWindow", "Create matrix 2 table"))
        self.cb_ch19.setItemText(10, _translate("MainWindow", "Create matrix 3 table"))
        self.cb_ch19.setItemText(11, _translate("MainWindow", "Create matrix 4 table"))
        self.cb_ch19.setItemText(12, _translate("MainWindow", "Create matrix 5 table"))
        self.cb_ch19.setItemText(13, _translate("MainWindow", "Create matrix 6 table"))
        self.cb_ch19.setItemText(14, _translate("MainWindow", "Create matrix 7 table"))
        self.cb_ch19.setItemText(15, _translate("MainWindow", "Create measures chapter"))
        self.bt_cons.setText(_translate("MainWindow", "Conservation status"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionAdd_site.setText(_translate("MainWindow", "Add site"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
