# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_v3.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1185, 910)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_info = QtWidgets.QLabel(self.centralwidget)
        self.lbl_info.setGeometry(QtCore.QRect(10, 10, 1171, 141))
        self.lbl_info.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_info.setObjectName("lbl_info")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 220, 491, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(700, 170, 20, 631))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(710, 690, 471, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(720, 170, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tb_save = QtWidgets.QToolButton(self.centralwidget)
        self.tb_save.setGeometry(QtCore.QRect(720, 210, 451, 41))
        self.tb_save.setObjectName("tb_save")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(10, 770, 451, 51))
        self.checkBox.setObjectName("checkBox")
        self.tb_img = QtWidgets.QToolButton(self.centralwidget)
        self.tb_img.setGeometry(QtCore.QRect(720, 260, 451, 41))
        self.tb_img.setObjectName("tb_img")
        self.tb_maps = QtWidgets.QToolButton(self.centralwidget)
        self.tb_maps.setGeometry(QtCore.QRect(720, 310, 451, 41))
        self.tb_maps.setObjectName("tb_maps")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 820, 1161, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.bt_main = QtWidgets.QPushButton(self.centralwidget)
        self.bt_main.setGeometry(QtCore.QRect(720, 710, 331, 91))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.bt_main.setFont(font)
        self.bt_main.setObjectName("bt_main")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 160, 481, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.site = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.site.setContentsMargins(0, 0, 0, 0)
        self.site.setObjectName("site")
        self.lbl_site = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_site.setObjectName("lbl_site")
        self.site.addWidget(self.lbl_site)
        self.cb_site = QtWidgets.QComboBox(self.layoutWidget)
        self.cb_site.setObjectName("cb_site")
        self.site.addWidget(self.cb_site)
        self.lgbx = QtWidgets.QTextBrowser(self.centralwidget)
        self.lgbx.setGeometry(QtCore.QRect(720, 380, 451, 311))
        self.lgbx.setObjectName("lgbx")
        self.bt_cons = QtWidgets.QPushButton(self.centralwidget)
        self.bt_cons.setGeometry(QtCore.QRect(1070, 710, 101, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bt_cons.setFont(font)
        self.bt_cons.setObjectName("bt_cons")
        self.base_lst = QtWidgets.QListWidget(self.centralwidget)
        self.base_lst.setGeometry(QtCore.QRect(10, 250, 300, 521))
        self.base_lst.setObjectName("base_lst")
        item = QtWidgets.QListWidgetItem()
        self.base_lst.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.base_lst.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.base_lst.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.base_lst.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.base_lst.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.base_lst.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.base_lst.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.base_lst.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.base_lst.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.base_lst.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.base_lst.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.base_lst.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.base_lst.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.base_lst.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.base_lst.addItem(item)
        self.doc_lst = QtWidgets.QListWidget(self.centralwidget)
        self.doc_lst.setGeometry(QtCore.QRect(400, 250, 300, 521))
        self.doc_lst.setObjectName("doc_lst")
        self.bt_allr = QtWidgets.QPushButton(self.centralwidget)
        self.bt_allr.setGeometry(QtCore.QRect(320, 260, 71, 23))
        self.bt_allr.setObjectName("bt_allr")
        self.bt_alll = QtWidgets.QPushButton(self.centralwidget)
        self.bt_alll.setGeometry(QtCore.QRect(320, 360, 71, 23))
        self.bt_alll.setObjectName("bt_alll")
        self.bt_oner = QtWidgets.QPushButton(self.centralwidget)
        self.bt_oner.setGeometry(QtCore.QRect(320, 290, 71, 23))
        self.bt_oner.setObjectName("bt_oner")
        self.bt_onel = QtWidgets.QPushButton(self.centralwidget)
        self.bt_onel.setGeometry(QtCore.QRect(320, 330, 71, 23))
        self.bt_onel.setObjectName("bt_onel")
        self.bt_up = QtWidgets.QPushButton(self.centralwidget)
        self.bt_up.setGeometry(QtCore.QRect(460, 780, 81, 23))
        self.bt_up.setObjectName("bt_up")
        self.bt_dw = QtWidgets.QPushButton(self.centralwidget)
        self.bt_dw.setGeometry(QtCore.QRect(570, 780, 81, 23))
        self.bt_dw.setObjectName("bt_dw")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(720, 360, 111, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1060, 850, 121, 16))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1185, 21))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAdd_site = QtWidgets.QAction(MainWindow)
        self.actionAdd_site.setObjectName("actionAdd_site")
        self.menuSettings.addAction(self.actionAdd_site)
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_info.setText(_translate("MainWindow", "Here is the informative text"))
        self.label.setText(_translate("MainWindow", "Doc format! (Choose the chapters/tables in the desired order)"))
        self.label_2.setText(_translate("MainWindow", "Options"))
        self.tb_save.setText(_translate("MainWindow", "Choose where to save the file!"))
        self.checkBox.setText(_translate("MainWindow", "I want empty tables! If checked the tables will be exported empty."))
        self.tb_img.setText(_translate("MainWindow", "Choose the species photos folder!"))
        self.tb_maps.setText(_translate("MainWindow", "Choose the species maps folder!"))
        self.bt_main.setText(_translate("MainWindow", "Create document!"))
        self.lbl_site.setText(_translate("MainWindow", "Select the site!"))
        self.bt_cons.setText(_translate("MainWindow", "Conservation"))
        __sortingEnabled = self.base_lst.isSortingEnabled()
        self.base_lst.setSortingEnabled(False)
        item = self.base_lst.item(0)
        item.setText(_translate("MainWindow", "Species header"))
        item = self.base_lst.item(1)
        item.setText(_translate("MainWindow", "Descriptive table A"))
        item = self.base_lst.item(2)
        item.setText(_translate("MainWindow", "Descriptive table B"))
        item = self.base_lst.item(3)
        item.setText(_translate("MainWindow", "Conservation table A"))
        item = self.base_lst.item(4)
        item.setText(_translate("MainWindow", "Matrix 1 table"))
        item = self.base_lst.item(5)
        item.setText(_translate("MainWindow", "Conservation table B"))
        item = self.base_lst.item(6)
        item.setText(_translate("MainWindow", "Matrix 2 table"))
        item = self.base_lst.item(7)
        item.setText(_translate("MainWindow", "Matrix 3 table"))
        item = self.base_lst.item(8)
        item.setText(_translate("MainWindow", "Conservation table C"))
        item = self.base_lst.item(9)
        item.setText(_translate("MainWindow", "Matrix 4 table"))
        item = self.base_lst.item(10)
        item.setText(_translate("MainWindow", "Matrix 5 table"))
        item = self.base_lst.item(11)
        item.setText(_translate("MainWindow", "Matrix 6 table"))
        item = self.base_lst.item(12)
        item.setText(_translate("MainWindow", "Conservation table D"))
        item = self.base_lst.item(13)
        item.setText(_translate("MainWindow", "Matrix 7 table"))
        item = self.base_lst.item(14)
        item.setText(_translate("MainWindow", "Measures chapter"))
        self.base_lst.setSortingEnabled(__sortingEnabled)
        self.bt_allr.setText(_translate("MainWindow", ">>"))
        self.bt_alll.setText(_translate("MainWindow", "<<"))
        self.bt_oner.setText(_translate("MainWindow", ">"))
        self.bt_onel.setText(_translate("MainWindow", "<"))
        self.bt_up.setText(_translate("MainWindow", "Up"))
        self.bt_dw.setText(_translate("MainWindow", "Down"))
        self.label_3.setText(_translate("MainWindow", "Log window"))
        self.label_4.setText(_translate("MainWindow", "@ Dorin Damoc - 2019"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionAdd_site.setText(_translate("MainWindow", "Add site"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
